language: java

dist: trusty

jdk:
# trying Travis JDK11 support again
  - openjdk11
  - oraclejdk8

services: mongodb

before_install:
  - sudo apt-get install jq
  - curl -LSs $(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("application/java-archive"))) | .[0].browser_download_url') -o codacy-coverage-reporter-assembly.jar

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

addons:
  sonarcloud:
    organization: "aidanwhiteley-github"

cache:
  directories:
  - $HOME/.m2

script:
  # other script steps might be done before running the actual analysis
  - git fetch --unshallow
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
